### ISSUE TITLE
hyper-startup in win environment with command line

### ISSUE THREAD

**Issue by levsthings** [curz46/hyper-startup#1]
## Details
- **Windows 10**
- **Hyper.app version**: 1.2.1
- **Gist for [hyper.js](https://gist.github.com/levsthings/bbb1635ded98d6897f7ec0da75bf31c6)**

## Issue
I'm trying to use hyper-startup to run a .bat file on startup so I can switch from cmd line to ConEmu automatically on startup. However I couldn't even get it to echo a message on startup, it seems like the arguments are not being passed at all.

Any ideas on how I could debug this?

**Comment by jaspinegz** [comment]
You've placed the `commands` configuration property inside the global object rather than the `config` object in your `hyper.js` :)
